on:
  workflow_dispatch:
    # Optional: Add inputs if your workflow requires them
    inputs:
      url:
        required: true

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ github.event.inputs.url }}'
